# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: # jekyll-seo-tag > Owners twitter username
author: lauralogozzo # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Laura Logozzo # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/lauralogozzo
    - https://github.com/lauralogozzo
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: New York City # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    feature_text: |
      
    feature_image: ""

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/images/Laura_Portrait2.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Laura Logozzo" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/laura-logo.svg" # Site logo, also used in jekyll-seo-tag
description: "" # Site description and default description, also used in jekyll-seo-tag
url: "lauralogozzo.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/lauralogozzo/lauralogozzo.github.io"
email: "laura.logozzo@uleth.ca"
# Google Analytics
google_analytics: 'G-KYCFGSLF7L'
google_analytics_anonymize_ip: 'TRUE'
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/watersample.png'
  32: '/assets/logos/watersample.png'
  96: '/assets/logos/watersample.png'
  120: '/assets/logos/watersample.png'
  144: '/assets/logos/watersample.png'
  180: '/assets/logos/watersample.png'
  512: '/assets/logos/watersample.png'
  1024: '/assets/logos/watersample.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Research
  url: /Research/
- title: Publications
  url: /Publications/
- title: Data & Code
  url: /Data/
- title: Contact Me
  url: /Contact/

navigation_footer:
- title: Site theme created by David Darnes
  url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: 
  LinkedIn: https://www.linkedin.com/in/lauralogozzo
  GitHub: https://github.com/lauralogozzo
  link: 
  RSS: 

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
